[project]
name = "sqlalchemy_14_migration_tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cryptography>=45.0.4",
    "mysqlclient==2.0.3",
    "sqlalchemy==1.3.24",
]
